---
name: Setup TS
on: [ workflow_call ]

jobs:
  Setup-TS:
    name: Setup TS
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install protoc-gen-js
        run: pnpm install -g protoc-gen-js
