name: Test go

on:
  push:
    branches: [ "main" ]
    paths:
      - go/**
      - proto/**
      - .github
  pull_request:
    branches: [ "main" ]
    paths:
      - go/**
      - proto/**
      - .github
  workflow_dispatch:

jobs:
  test_go:
    name: Test go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.23'

      - name: Install protoc-gen-go-grpc
        run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Test
        run: make protoc test-go
